
module.exports = {
	USER_VERIFY:"USER_VERIFY",
	JOIN_LOBBY:"JOIN_LOBBY",
	NEW_USER_LOBBY:"NEW_USER_LOBBY",
	CREATE_GAME:"CREATE_GAME",
	JOIN_GAME:"JOIN_GAME",
	NEW_GAME_CREATED: "NEW_GAME_CREATED",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	LOGOUT:"LOGOUT"
}
